require:
  - rubocop-rspec
  - rubocop/rspec/focused

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'config/initializers/simple_form_bootstrap.rb'

Metrics/LineLength:
  Max: 100

Metrics/ModuleLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Documentation:
  Enabled: false
